export const GET_APP_DATA_SUCCEEDED = 'GET_APP_DATA_SUCCEEDED';
export const POST_APP_DATA_SUCCEEDED = 'POST_APP_DATA_SUCCEEDED';
export const FLAG_PATCHING_APP_DATA = 'FLAG_PATCHING_APP_DATA';
export const PATCH_APP_DATA_FAILED = 'PATCH_APP_DATA_FAILED';
export const PATCH_APP_DATA_SUCCEEDED = 'PATCH_APP_DATA_SUCCEEDED';
export const FLAG_GETTING_APP_DATA = 'FLAG_GETTING_APP_DATA';
export const GET_APP_DATA_FAILED = 'GET_APP_DATA_FAILED';
export const POST_APP_DATA_FAILED = 'POST_APP_DATA_FAILED';
