// context
export const FLAG_GETTING_CONTEXT = 'FLAG_GETTING_CONTEXT';
export const GET_CONTEXT_SUCCEEDED = 'GET_CONTEXT_SUCCEEDED';
export const GET_CONTEXT_FAILED = 'GET_CONTEXT_FAILED';
export const GET_CONTEXT = 'GET_CONTEXT';
export const GET_AUTH_TOKEN_SUCCEEDED = 'GET_AUTH_TOKEN_SUCCEEDED';
export const FLAG_GETTING_AUTH_TOKEN = 'FLAG_GETTING_AUTH_TOKEN';
export const GET_AUTH_TOKEN = 'GET_AUTH_TOKEN';
